### ISSUE TITLE
Version 1.2.5 broken

### ISSUE THREAD

**Issue by borupdaniel** [conda-forge/gpi-feedstock#29]
Hi @conda-forge/core,

Please move version 1.2.5 (both builds) of this package from ``main`` to ``broken`` on the conda-forge channel on anaconda.org because:

This version had a bug that could cause crashes for some users, and prevents building the downstream package `gpi_core`

**Comment by xhochy** [comment]
@borupdaniel Please make a PR to https://github.com/conda-forge/cf-mark-broken for this.

**Comment by borupdaniel** [comment]
Will do, thanks!
