### ISSUE TITLE
Remove build 0 for v1.0.6

### ISSUE THREAD

**Issue by borupdaniel** [conda-forge/gpi-feedstock#3]
Hi @conda-forge/core 

I'm a bit new to conda recipes and accidentally uploaded a build with a recipe that allows our package to be installed with an incompatible version of python. Could you please delete the following build so that it's not installed by mistake into an environment with python2?

```
# Name                       Version           Build  Channel             
gpi                            1.0.6               0  conda-forge
```

Thanks!

**Comment by jjhelmus** [comment]
@borupdaniel I moved the build 0 packages to the `broken` label.  These will not be installed unless a user explicitly adds this label.  We prefer this to outright deleting the packages.

**Comment by borupdaniel** [comment]
Perfect, thanks! I wasn't sure if that was possible for an individual build or just the package as a whole.
